export const BANGLADESH_RAILWAY_STATIONS = [
  "Dhaka",
  "Chattogram",
  "Sylhet",
  "Rajshahi",
  "Khulna",
  "Rangpur",
  "Barishal",
  "Mymensingh",
  "Cumilla",
  "Gazipur",
  "Narayanganj",
  "Bogura",
  "Noakhali",
  "Feni",
  "Chandpur",
  "Brahmanbaria",
  "Kishoreganj",
  "Tangail",
  "Jamalpur",
  "Sirajganj",
  "Pabna",
  "Ishwardi",
  "Kushtia",
  "Jashore",
  "Benapole",
  "Dinajpur",
  "Lalmonirhat",
  "Gaibandha",
  "Thakurgaon",
  "Panchagarh",
  "Netrokona",
  "Akhaura",
  "Laksam",
  "Bhairab Bazar",
  "Srimangal",
  "Kulaura",
  "Shaistaganj",
  "Ashuganj",
  "Tongi",
  "Joydebpur",
] as const;

export type RailwayStation = (typeof BANGLADESH_RAILWAY_STATIONS)[number];
