name: Node.js CD (Auto Deploy)

on:
  push:
    branches:
      - develop  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploying to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /projects/shikkhapath.com  # Apnar server-e project folder-er path
            git clean -fd
            git pull origin develop
            rm -rf .next node_modules
            npm ci
            npm run build
            pm2 restart SHIKKHAPATH || pm2 start ecosystem.config.js # PM2-te je name deya ache